#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
# Source0 file verified with key 0xE9CBDFC0ABC0A854 (scdbackup@gmx.net)
#
Name     : libburn
Version  : 1.5.0
Release  : 5
URL      : http://files.libburnia-project.org/releases/libburn-1.5.0.tar.gz
Source0  : http://files.libburnia-project.org/releases/libburn-1.5.0.tar.gz
Source99 : http://files.libburnia-project.org/releases/libburn-1.5.0.tar.gz.asc
Summary  : Library to read/write optical discs
Group    : Development/Tools
License  : GPL-2.0
Requires: libburn-bin
Requires: libburn-lib
Requires: libburn-license
Requires: libburn-man
BuildRequires : pkgconfig(libcdio)

%description
------------------------------------------------------------------------------
libburnia-project.org
------------------------------------------------------------------------------
This all is under GPL.
(See GPL reference, our clarification and commitment at the end of this text)
------------------------------------------------------------------------------
libburnia-project.org
By Mario Danic <mario.danic@gmail.com> and Thomas Schmitt <scdbackup@gmx.net>
Still containing parts of Libburn. By Derek Foreman <derek@signalmarketing.com>
and Ben Jansens <xor@orodu.net>

%package bin
Summary: bin components for the libburn package.
Group: Binaries
Requires: libburn-license
Requires: libburn-man

%description bin
bin components for the libburn package.


%package dev
Summary: dev components for the libburn package.
Group: Development
Requires: libburn-lib
Requires: libburn-bin
Provides: libburn-devel

%description dev
dev components for the libburn package.


%package lib
Summary: lib components for the libburn package.
Group: Libraries
Requires: libburn-license

%description lib
lib components for the libburn package.


%package license
Summary: license components for the libburn package.
Group: Default

%description license
license components for the libburn package.


%package man
Summary: man components for the libburn package.
Group: Default

%description man
man components for the libburn package.


%prep
%setup -q -n libburn-1.5.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1537206450
%configure --disable-static
make  %{?_smp_mflags}

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make VERBOSE=1 V=1 %{?_smp_mflags} check

%install
export SOURCE_DATE_EPOCH=1537206450
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/doc/libburn
cp COPYING %{buildroot}/usr/share/doc/libburn/COPYING
cp COPYRIGHT %{buildroot}/usr/share/doc/libburn/COPYRIGHT
%make_install

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/cdrskin

%files dev
%defattr(-,root,root,-)
/usr/include/libburn/libburn.h
/usr/lib64/libburn.so
/usr/lib64/pkgconfig/libburn-1.pc

%files lib
%defattr(-,root,root,-)
/usr/lib64/libburn.so.4
/usr/lib64/libburn.so.4.103.0

%files license
%defattr(-,root,root,-)
/usr/share/doc/libburn/COPYING
/usr/share/doc/libburn/COPYRIGHT

%files man
%defattr(-,root,root,-)
/usr/share/man/man1/cdrskin.1
